language: node_js
dist: trusty
node_js:
- "12"
- "11"
- "10"
- "9"
- "8"
install:
- npm i
script:
- npm run check-commit
- npm run build
after_script:
# Generate coverage report
- npm run coverage
# Update coverage report
- $(npm bin)/codecov