jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        npm install
        npm run build
        npm run check-commit
    - uses: codecov/codecov-action@v1
name: build
on:
  - pull_request
  - push